### ISSUE TITLE
Error related to size dismatch when running `play.py`

### ISSUE THREAD

**Issue by tegg89** [takuseno/rsvg#1]
Hi, thanks for sharing the code.
I am recently trying to implement SVG with your repository as a reference.
I could have run `train.py` to create the trained model (only created metafile for unknown reason), however when I run `play.py`, the error related to size mismatch has occurred.
At first, I have changed the observation dimension to the size of `train.py` has used. But the problem has not resolved in extracting corresponded action value.
I am using TF version 1.4, but I don't think the reason is the difference of version. Does the `play.py` work your machine?

**Comment by takuseno** [comment]
@tegg89 
thank you for trying my codes! Sorry for inconvenience about that. I'll clean the codes later and notify you!

**Comment by takuseno** [comment]
@tegg89 
Sorry for dealing with this problem late. Now I refactored all the codes here. You can evaluate your trained model by following command.

```
$ python train.py --load {path to model} --demo
```

Thank you!

**Comment by tegg89** [comment]
@takuseno 
Thanks for your reply. I have tried your works but still matching file error has happened.
The error message says that the `TensorSliceReader constructor` cannot find any matching file in the `result` folder.
Is there any missing part while following the revised instruction?
Also, my experimented environment is `python3` and `TF ver. 1.7`.

Thanks in advance.

**Comment by takuseno** [comment]
@tegg89 
 I suppose that there is directories like `results/2018*****` and model files like `model.ckpt-****.data-00000-of-00001`, `model.ckpt-****.meta`, `model.ckpt-****.index`. Then, the path should be like this
```
$ python train.py --load results/subdirectory/model.ckpt-**** # this stars should be replaced with timestep
```

**Comment by tegg89** [comment]
Which version of tensorflow do you use? I still cannot figure out the correct load process.
While I follow your steps, data loss error came up. Which means the different restore operator and file format are used. The part of the error message is shown below:
```
DataLossError (see above for traceback): Unable to open table file ./results/20180503113259/model.ckpt-1190.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]
	 [[Node: save/RestoreV2/_149 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_154_save/RestoreV2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]
```

**Comment by takuseno** [comment]
could you give me the exact code on your shell? I think the version of tensorflow doesn't matter here.

**Comment by tegg89** [comment]
Training: `python train.py --final-steps 1000`
- I have decreased the number of final steps due to checking whether loading the trained model work.
- If I add render option, I am able to watch the training process.

Testing: `python train.py --load results/20180504143655/model.ckpt-1190.data-00000-of-00001`

**Comment by takuseno** [comment]
can you try this?
```
python train.py --load results/20180504143655/model.ckpt-1190
```

**Comment by tegg89** [comment]
@takuseno 
It works! Now I would like to study with this repository. 
Thanks a lot for your kind reply.
